version: 0.1

phases:
  install: 
    commands:
      - go get -u github.com/golang/lint/golint
      - go get -u github.com/tools/godep

  pre_build: 
    commands:
      - go version
      - golint -set_exit_status
      - godep restore

  build:
    commands:
      - go build -v -o build/rt_api_prototype-$CODEBUILD_SOURCE_VERSION

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/*
