version: 0.1

phases:
  build:
    commands:
      - go version
      - go get github.com/gorilla/mux
      - go build -v main.go 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - rt_api_prototype