version: 0.1

phases:
  install: 
    commands:
      - go get -u github.com/gorilla/mux
      - go get -u github.com/golang/lint/golint

  pre_build: 
    commands:
      - go version
      - golint -set_exit_status

  build:
    commands:
      - go build -v -o rt_api_prototype

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - rt_api_prototype